"""Added created and submitted on to donation model

Revision ID: 7ca14348db44
Revises: 9879debcb49d
Create Date: 2020-04-19 18:36:39.655160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ca14348db44'
down_revision = '9879debcb49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('donations', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('donations', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('donations', 'updated_on')
    op.drop_column('donations', 'created_on')
    # ### end Alembic commands ###
