"""Added appeal relationship to lead

Revision ID: 9879debcb49d
Revises: dfa904a56e10
Create Date: 2020-04-19 14:34:43.516482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9879debcb49d'
down_revision = 'dfa904a56e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('appeal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'appeals', ['appeal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'appeal_id')
    # ### end Alembic commands ###
