"""Initial migration

Revision ID: dfa904a56e10
Revises: 
Create Date: 2020-04-17 17:35:42.896662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfa904a56e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('date', sa.String(length=20), nullable=True))
    op.add_column('calls', sa.Column('time', sa.String(length=20), nullable=True))
    op.drop_column('calls', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('calls', 'time')
    op.drop_column('calls', 'date')
    # ### end Alembic commands ###
